# Generated by Django 3.0.14 on 2021-06-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210602_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=25570000000, help_text='+2557000000', max_length=25),
        ),
    ]
